# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 33) do

  create_table "booking_sources", :force => true do |t|
    t.column "source", :string
  end

  create_table "cash_ups", :force => true do |t|
    t.column "till_ip",       :string
    t.column "user_id",       :integer
    t.column "time",          :datetime
    t.column "cash_amount",   :decimal,  :precision => 10, :scale => 2
    t.column "card_amount",   :decimal,  :precision => 10, :scale => 2
    t.column "cheque_amount", :decimal,  :precision => 10, :scale => 2
  end

  create_table "certificates", :force => true do |t|
    t.column "name", :string
  end

  create_table "consumables", :force => true do |t|
    t.column "name",          :string
    t.column "stock_level",   :integer
    t.column "reorder_level", :integer
    t.column "desired_level", :integer
  end

  create_table "consumables_products", :id => false, :force => true do |t|
    t.column "consumable_id", :integer
    t.column "product_id",    :integer
  end

  add_index "consumables_products", ["consumable_id"], :name => "fk_consumables_products_consumable"
  add_index "consumables_products", ["product_id"], :name => "fk_consumables_products_product"

  create_table "customers", :force => true do |t|
    t.column "name",      :string
    t.column "telephone", :string
    t.column "email",     :string
  end

  create_table "films", :force => true do |t|
    t.column "title",          :string
    t.column "length",         :integer
    t.column "certificate_id", :integer
  end

  add_index "films", ["certificate_id"], :name => "fk_film_certificate"

  create_table "offer_sales", :force => true do |t|
    t.column "offer_id",      :integer
    t.column "sale_id",       :integer
    t.column "refund_amount", :decimal, :precision => 10, :scale => 2
  end

  add_index "offer_sales", ["offer_id"], :name => "fk_offer_sale"
  add_index "offer_sales", ["sale_id"], :name => "fk_sale_offer"

  create_table "offers", :force => true do |t|
    t.column "name",          :string
    t.column "refund_amount", :decimal, :precision => 10, :scale => 2
    t.column "description",   :string
    t.column "automatic",     :boolean
    t.column "available",     :boolean
  end

  create_table "other_product_sales", :force => true do |t|
    t.column "product_id", :integer
    t.column "sale_id",    :integer
    t.column "price",      :decimal, :precision => 10, :scale => 2
  end

  add_index "other_product_sales", ["product_id"], :name => "fk_other_product_sale"
  add_index "other_product_sales", ["sale_id"], :name => "fk_sale_other_product"

  create_table "payment_methods", :force => true do |t|
    t.column "name", :string
  end

  create_table "preferences", :force => true do |t|
    t.column "setting", :string
    t.column "value",   :string
  end

  create_table "product_offers", :force => true do |t|
    t.column "product_id",        :integer
    t.column "offer_id",          :integer
    t.column "quantity_required", :integer
  end

  add_index "product_offers", ["product_id"], :name => "fk_product_offer"
  add_index "product_offers", ["offer_id"], :name => "fk_offer_product"

  create_table "products", :force => true do |t|
    t.column "name",                :string
    t.column "price",               :decimal, :precision => 10, :scale => 2
    t.column "type",                :string
    t.column "barcode",             :string
    t.column "available",           :boolean,                                :default => true
    t.column "refreshment_type_id", :integer
    t.column "stock_level",         :integer
    t.column "reorder_level",       :integer
    t.column "desired_level",       :integer
    t.column "display_in_second_screen_list", :boolean
  end

  create_table "refreshment_sales", :force => true do |t|
    t.column "refreshment_id", :integer
    t.column "sale_id",        :integer
    t.column "price",          :decimal, :precision => 10, :scale => 2
  end

  add_index "refreshment_sales", ["refreshment_id"], :name => "fk_refreshment_sale"
  add_index "refreshment_sales", ["sale_id"], :name => "fk_sale_refreshment"

  create_table "refreshment_types", :force => true do |t|
    t.column "name", :string
  end

  create_table "sales", :force => true do |t|
    t.column "type",              :string
    t.column "sale_time",         :datetime
    t.column "user_id",           :integer
    t.column "payment_method_id", :integer
    t.column "tendered",          :decimal,  :precision => 10, :scale => 2
    t.column "till_ip",           :string
    t.column "card_surcharge",    :decimal,  :precision => 10, :scale => 2, :default => 0.0
    t.column "cheque_surcharge",  :decimal,  :precision => 10, :scale => 2, :default => 0.0
    t.column "refunded",          :boolean,                                 :default => false
    t.column "customer_id",       :integer
    t.column "booking_source_id", :integer
    t.column "collected",         :boolean
  end

  create_table "screens", :force => true do |t|
    t.column "name", :string
  end

  create_table "screens_showings", :id => false, :force => true do |t|
    t.column "showing_id", :integer
    t.column "screen_id",  :integer
  end

  add_index "screens_showings", ["screen_id"], :name => "fk_showing_screen"
  add_index "screens_showings", ["showing_id"], :name => "fk_screen_showing"

  create_table "seat_reservations", :force => true do |t|
    t.column "seat_id",       :integer
    t.column "showing_id",    :integer
    t.column "sale_id",       :integer
    t.column "time_reserved", :datetime
  end

  add_index "seat_reservations", ["seat_id"], :name => "fk_seat_reservation_seat"
  add_index "seat_reservations", ["showing_id"], :name => "fk_seat_reservation_showing"

  create_table "seats", :force => true do |t|
    t.column "row",       :string
    t.column "column",    :string
    t.column "x_pos",     :decimal, :precision => 10, :scale => 2
    t.column "y_pos",     :decimal, :precision => 10, :scale => 2
    t.column "screen_id", :integer
  end

  add_index "seats", ["screen_id"], :name => "fk_seat_screen"

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "showings", :force => true do |t|
    t.column "film_id",   :integer
    t.column "show_time", :datetime
  end

  add_index "showings", ["film_id"], :name => "fk_showing_film"

  create_table "staff_events", :force => true do |t|
    t.column "user_id", :integer
    t.column "type",    :string
    t.column "time",    :datetime
  end

  add_index "staff_events", ["user_id"], :name => "fk_staff_event_user"

  create_table "temp_tickets", :force => true do |t|
    t.column "ticket_type_allocation_id", :integer
    t.column "time_reserved",             :datetime
    t.column "seat_number",               :integer
  end

  create_table "ticket_sales", :force => true do |t|
    t.column "ticket_id", :integer
    t.column "sale_id",   :integer
    t.column "price",     :decimal, :precision => 10, :scale => 2
  end

  add_index "ticket_sales", ["ticket_id"], :name => "fk_ticket_sale"
  add_index "ticket_sales", ["sale_id"], :name => "fk_sale_ticket"

  create_table "ticket_type_allocations", :force => true do |t|
    t.column "ticket_type_id", :integer,                 :null => false
    t.column "showing_id",     :integer,                 :null => false
    t.column "max_number",     :integer, :default => -1
  end

  add_index "ticket_type_allocations", ["ticket_type_id"], :name => "fk_priceband_showing"
  add_index "ticket_type_allocations", ["showing_id"], :name => "fk_showing_priceband"

  create_table "tickets", :force => true do |t|
    t.column "showing_id",     :integer
    t.column "ticket_type_id", :integer
  end

  add_index "tickets", ["ticket_type_id"], :name => "fk_ticket_ticket_type"
  add_index "tickets", ["showing_id"], :name => "fk_ticket_showing"

  create_table "users", :force => true do |t|
    t.column "first_name",            :string
    t.column "last_name",             :string
    t.column "username",              :string
    t.column "hashed_pin",            :string
    t.column "saved_session",         :text
    t.column "last_login",            :datetime
    t.column "type",                  :string
    t.column "hashed_admin_password", :string
  end

end
